### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: mimic_all  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 1024
max_samples: 173249
overwrite_cache: true
preprocessing_num_workers: 8
# streaming: true
# max_steps: 60000

### output
output_dir: saves/qwen2_vl-7b/lora/sft/mimic_only
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
